In [1]:
import numpy as np         #importing numpy library

In [15]:
a0=np.array(20)             #  0d array
a0

array(20)

In [16]:
a1=np.array([1,2,3,4,5])  # 1d array creation

In [17]:
a1

array([1, 2, 3, 4, 5])

In [18]:
a2=np.array([[1,2,3],[4,5,6]])   #2d array creation

In [19]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])   #3d array creation

In [21]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
print(type(a1))          #type of array

<class 'numpy.ndarray'>


In [27]:
print(a1.ndim)
print(a2.ndim)             #to check number of dimensions
print(a3.ndim)

1
2
3


In [28]:
#Accessing array elements

In [33]:
print(a1[0])          #accessing 1st element in 1d array
print(a1[-1])         #negative index starts from the end

1
5


In [31]:
print(a2[1,1])      #accessing 2nd dim 2nd element in 2d array

5


In [32]:
print(a3[0,1,2])    #accessing 3rd element of second array of first array

6


In [34]:
#slicing arrays

In [42]:
print(a1[1:3])       #printing elements whose index starts from 1 till 3 and 3 is not included
print(a1[:2])        #by default starting value is 0
print(a1[1:])        #by default ending will be last element of array

[2 3]
[1 2]
[2 3 4 5]


In [44]:
print(a2[1,1:3]) 

[5 6]


In [45]:
print(a1.dtype)

int32


In [49]:
b=np.array([1,2,3],float)

In [47]:
b

array([1., 2., 3.])

In [48]:
print(b.dtype)

float64


In [50]:
print(a1.shape)       #returns a tuple with each index having number of elements 

(5,)


In [51]:
print(a2.shape)

(2, 3)


In [52]:
print(a3.shape)

(2, 2, 3)


In [53]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [55]:
newarr=arr.reshape(4,3)             #reshaping chsnging the dimensions

In [56]:
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
print(newarr.reshape(-1))           #flattening the array(changing multidimension array to 1d array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [58]:
#Iterating arrays

In [59]:
for i in a1:
    print(i)            #iterarting 1d array

1
2
3
4
5


In [61]:
for i in a2:
    print(i)           #iterarting 2d array

[1 2 3]
[4 5 6]


In [62]:
for i in a2:
    for j in i:
        print(j)             #iterarting 2d array

1
2
3
4
5
6


In [63]:
for i in a3:
    for j in i:
        for k in j:           #iterarting 3d array
            print(k)
            

1
2
3
4
5
6
7
8
9
10
11
12


In [64]:
#above all take much time for high dimension arrays

In [65]:
#now using a function to iterate called nditer()

In [66]:
for i in np.nditer(a1):
    print(i)

1
2
3
4
5


In [67]:
for i in np.nditer(a2):
    print(i)

1
2
3
4
5
6


In [68]:
for i in np.nditer(a3):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [69]:
# to get index along with value use ndenumerate()

In [70]:
for index,i in np.ndenumerate(a2):
    print(index,i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [73]:
print(len(a1))             #to get number of elements in a array
print(len(a2))
print(len(a3))

5
2
2


In [74]:
pavan=np.array([1,2,3,4,5])

In [75]:
pavan.tolist()             #to convert array to list

[1, 2, 3, 4, 5]

In [76]:
pavan.tostring()

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00'

In [77]:
# ways of creating arrays

In [78]:
sam=np.arange(6)

In [79]:
sam

array([0, 1, 2, 3, 4, 5])

In [81]:
s=np.arange(6,dtype=float)

In [82]:
s

array([0., 1., 2., 3., 4., 5.])

In [83]:
sp=np.arange(6).reshape(2,3)

In [84]:
sp

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
#creating arrays of zeroes and ones

In [90]:
a=np.ones(4,dtype=int)

In [91]:
a

array([1, 1, 1, 1])

In [92]:
b=np.zeros(5)

In [93]:
b

array([0., 0., 0., 0., 0.])

In [94]:
#to create identity matrix

In [95]:
i=np.identity(4)

In [96]:
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [98]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [99]:
a+b

array([ 7,  9, 11, 13, 15])

In [100]:
a-b

array([-5, -5, -5, -5, -5])

In [101]:
a*b

array([ 6, 14, 24, 36, 50])

In [102]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [103]:
a%b

array([1, 2, 3, 4, 5], dtype=int32)

In [104]:
# basic array operations

In [110]:
a=np.array([2,3,4,5],float)

In [111]:
a.sum()

14.0

In [112]:
np.sqrt(a)

array([1.41421356, 1.73205081, 2.        , 2.23606798])

In [113]:
np.sort(a)

array([2., 3., 4., 5.])

In [115]:
c=np.array([1.1,2.3,4.5,6.7])

In [116]:
c

array([1.1, 2.3, 4.5, 6.7])

In [117]:
np.floor(c)

array([1., 2., 4., 6.])

In [118]:
np.ceil(c)

array([2., 3., 5., 7.])

In [123]:
np.rint(c)

array([1., 2., 4., 7.])

In [124]:
a.prod()

120.0

In [125]:
k=np.array([1,3,5,7,9])

In [126]:
k.mean()

5.0

In [127]:
k.var()

8.0

In [128]:
k.std()

2.8284271247461903

In [129]:
k.min()

1

In [130]:
k.max()

9

In [131]:
k.sort()

In [132]:
k

array([1, 3, 5, 7, 9])

In [133]:
k.argmin()

0

In [134]:
k.argmax()

4

In [135]:
u=np.array([1,1,1,1,1,1,2,3,4,5,5,5])

In [136]:
np.unique(u)

array([1, 2, 3, 4, 5])

In [137]:
#diff between copy and view:
#  copy is a new array
#  view is just a view of original array
# the copy owns the data and any changes made to the copy will not affect original array and vice versa
#  the view doesnot own data and any change s made will reflect




In [138]:
a=np.array([4,7,8])

In [139]:
b=a.copy()

In [140]:
a[0]=9

In [141]:
print(a)

[9 7 8]


In [142]:
print(b)

[4 7 8]


In [143]:
a=np.array([2,4,6])

In [144]:
b=a.view()

In [145]:
a[0]=8

In [146]:
print(a)

[8 4 6]


In [147]:
print(b)

[8 4 6]


In [148]:
#the changes made to the copy will not affect and when it comes to view the data effects

In [149]:
# to check if array owns the data

In [ ]:
#base is a attribute that returns null if it owns data else it returns same array

In [150]:
h=np.array([1,2,3,4,5])

In [151]:
x=h.copy()
y=h.view()

In [152]:
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [153]:
# copy returns none so it owns data and view returns original array so it doesnot owns the data

In [154]:
#ufuncs are universal functions and they are numpy functions that operates on the nd object

In [155]:
a=np.array([10,2,4,5,8])

In [156]:
b=np.array([2,3,8,3,4])

In [158]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.power(a,b))
print(np.mod(a,b))
print(np.remainder(a,b))
print(np.divmod(a,b))


[ 3  5 11  7  9]
[-1 -1 -5  1  1]
[ 2  6 24 12 20]
[0.5        0.66666667 0.375      1.33333333 1.25      ]
[   1    8 6561   64  625]
[1 2 3 1 1]
[1 2 3 1 1]
(array([0, 0, 0, 1, 1], dtype=int32), array([1, 2, 3, 1, 1], dtype=int32))


In [159]:
k=np.array([-1,-5,-8])
print(np.absolute(k))

[1 5 8]


In [161]:
print(np.sum([a,b]))

35


In [162]:
print(np.cumsum(a))

[ 1  3  6 10 15]


In [163]:
print(np.prod(a))

120


In [164]:
print(np.prod([a,b]))

69120


In [165]:
print(np.cumprod(a))

[  1   2   6  24 120]


In [168]:
print(np.diff([a,b]))

[[ 1  1  1  1]
 [ 1  5 -5  1]]


In [169]:
a=2
b=3
print(np.lcm(a,b))

6


In [170]:
print(np.gcd(a,b))

1


In [171]:
# we need to use reduce method to find lcm,gcd with arrays

In [174]:
a=np.array([1,2,3,4,5])
print(np.lcm.reduce(a))

60


In [175]:
print(np.gcd.reduce(a))

1
